# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- azure-pipelines

pr: none

variables:
- group: Passwords

resources:
  repositories:
  - repository: sys_kubernetes_templates
    type: bitbucket
    endpoint: Bitbucket - sistemas
    name: situm/sys-kubernetes-templates.git
    ref: SIS-144

jobs:

- job: Ios_job
  pool:
    vmImage: 'macOS-10.14'
    
  steps:
   - template: azure-templates/upload-sharepoint.yml@sys_kubernetes_templates
     parameters:
       prepare_sharepoint: False
       properties_file: 'scripts/framework.properties'
       prepare_ndk: false
    
   - script: |
      if [ "$(branch)" == "master-release" ] || [ "$(branch)" == "master" ] || [ $(echo $(branch) | grep -cE "^release-*") -eq 1 ];then
        buildType="Release"
      else
        buildType="Debug"
      fi
       echo "##vso[task.setvariable variable=buildType]$(echo $buildType)"
     displayName: Set buildType
    
  